Update

diff --git a/Makefile_for_Projects b/Makefile_for_Projects
--- a/Makefile_for_Projects
+++ b/Makefile_for_Projects
@@ -1,18 +1,18 @@
 # **************************************************************************** #
 #                                                                              #
 #                                                         :::      ::::::::    #
-#    Makefile                                           :+:      :+:    :+:    #
+#    Makefile_for_Projects                              :+:      :+:    :+:    #
 #                                                     +:+ +:+         +:+      #
 #    By: macarval <macarval@student.42sp.org.br>    +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/03/19 16:33:22 by macarval          #+#    #+#              #
-#    Updated: 2024/09/19 16:47:36 by macarval         ###   ########.fr        #
+#    Updated: 2024/10/25 08:32:26 by macarval         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
 NAME		=
 
-SRCS		= main.cpp *.cpp
+SRCS		= main.cpp
 
 VPATH		= src/
 OBJS_PATH	= obj
@@ -28,15 +28,6 @@ BLUE		= \033[0;34m
 MAGENTA		= \033[0;35m
 CYAN		= \033[0;36m
 RESET		= \033[0m
-
-# Bold
-BRED		= \033[1;31m
-BGREEN		= \033[1;32m
-BYELLOW		= \033[1;33m
-BBLUE		= \033[1;34m
-BPURPLE		= \033[1;35m
-BCYAN		= \033[1;36m
-BWHITE		= \033[1;37m
 
 OBJS 		= $(addprefix $(OBJS_PATH)/, $(SRCS:.cpp=.o))
 
@@ -77,32 +68,34 @@ val:
 
 git:
 			clear
-			@make fclean
-			git add .
-			git status
-			@echo "$(GREEN)Enter cpp list:"
-			@read list; \
-			echo -n "\n"; \
-			echo "$(YELLOW)Enter the exercise:"; \
-			read ex; \
-			echo -n "\n"; \
-			echo "$(MAGENTA)Choose status:"; \
-			echo "1. Init."; \
-			echo "2. In Progress..."; \
-			echo "3. Done!!"; \
-			echo "4. Correction"; \
-			echo "5. Bonus"; \
-			read status_choice; \
-			case $$status_choice in \
-						1) status="Init." ;; \
-						2) status="In Progress..." ;; \
-						3) status="Done!!" ;; \
-						4) status="Correction" ;; \
-						5) status="Bonus" ;; \
-						*) echo "Escolha inválida"; exit 1 ;; \
+			@make --no-print-directory fclean
+			@git add .
+			@git status
+			@echo "$(BPURPLE)Choose the commit type:"; \
+			echo "$(BYELLOW)1. feat: $(WHITE)Adds a new feature to your codebase"; \
+			echo "$(BYELLOW)2. fix: $(WHITE)Solves a problem in your codebase"; \
+			echo "$(BYELLOW)3. docs: $(WHITE)Documentation changes"; \
+			echo "$(BYELLOW)4. style: $(WHITE)Formatting, spacing, etc."; \
+			echo "$(BYELLOW)5. refactor: $(WHITE)Refactoring code used in production, e.g. renaming a variable"; \
+			echo "$(BYELLOW)6. test: $(WHITE)Adding tests, refactoring tests"; \
+			echo "$(BYELLOW)7. chore: $(WHITE)Adjust build script, updating dependencies, makefile etc"; \
+			read type_choice; \
+			case $$type_choice in \
+						1) type="feat" ;; \
+						2) type="fix" ;; \
+						3) type="docs" ;; \
+						4) type="style" ;; \
+						5) type="refactor" ;; \
+						6) type="test" ;; \
+						7) type="chore" ;; \
+						*) echo "$(BRED)Invalid choice"; exit 1 ;; \
 			esac; \
-			echo "$(BLUE)"; \
-			git commit -m "[OPP$$list]: ex$$ex $$status"
+			echo -n "\n"; \
+			echo "$(BGREEN)Enter the commit message:"; \
+			read msg; \
+			echo -n "\n"; \
+			echo "$(BBLUE)"; \
+			git commit -m "[ft_irc] $$type: $$msg"; \
 			git push
 
 .PHONY:		all re clean fclean comp val git
